artifact_location: file:///D:/ML PROJECTS/pearls-aqi-predictor/your-tracking-server-uri/0
creation_time: 1771106223364
experiment_id: '0'
last_update_time: 1771106223364
lifecycle_stage: active
name: Default
